apiVersion: argoproj.io/v1alpha1 
kind: Rollout 
metadata:
  name: sample-api-rollout
  namespace: api
  labels:
    app: sample-api
    
   
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sample-api
  template:
    metadata:
      labels:
        app: sample-api
         
    spec:
      containers:
      - name: sample-api
        # image: saturn203/sample-api
        image: nginx
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary: 
          steps:
          - setWeight: 25
          - pause: {}
          - setWeight: 50
          - pause: {} 
          - setWeight: 75
          - pause: {}
         
          


  
        